#:schema https://jj-vcs.github.io/jj/latest/config-schema.json
--when.repositories = [ "~/devel/hashicorp"]

[user]
email = "rselbach@hashicorp.com"
name = "Roberto Selbach"


[signing]
behavior = "own"
backend = "gpg"
key ="0ECFD015DAF6B114"


